name: Build and deploy Node.js app to Azure Web App - bluesitthimon-copy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        working-directory: ./my-app

      - name: Zip artifact for deployment
        run: zip -r release.zip ./
        working-directory: ./my-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: my-app/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C0D92E5C31B4EDDB34E0F1F2A5F05CD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03EE8B32717349288A15BF9104A114FC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B96930D877C04D9787718A4B8083B1B1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bluesitthimon-copy'
          slot-name: 'Production'
          package: .
